logging:
    level:
        root: INFO

server:
    #该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败，只有特殊需求的情况下才配置
    #address: 192.168.16.11
    port: 8080
    session-timeout: 60
    tomcat:
        max-threads: 100
        uri-encoding: UTF-8
    servlet:
        context-path: /efadmin_pay
